<h3>This new page is generated by CRM/Gittest/Page/GITtestpage.php</h3>

{* Example: Display a variable directly *}
<p>The current time is {$currentTime}</p>

<p>Line added and modified by Ruud</p>

{* Example: Display a translated string -- which happens to include a variable *}
<p>{ts 1=$currentTime}(In your native language) The current time is %1.{/ts}</p>